image: drupalpod/drupalpod-gitpod-base:20231222

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - init: |
      ddev start -y
      ddev composer remove drupal/core-dev
      ddev composer install --no-dev
      ddev drush si -y --account-pass=admin --site-name='ddev_gitpod' standard
      ddev drush en -y admin_toolbar admin_toolbar_tools
      ddev drush en -y package_manager project_browser
      ddev drush -y config:set project_browser.admin_settings allow_ui_install true
      ddev drush -y config:set --input-format=yaml package_manager.settings additional_trusted_composer_plugins \[tbachert/spi\]
      ddev drush cr
    command: |
      ddev start -y
      gp ports await 8080 && gp preview $(gp url 8080)

# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - andrewdavidblum.drupal-smart-snippets

    # Twig extensions.
    - mblode.twig-language-2

    # Bash extensions.
    - timonwong.shellcheck
    - rogalmic.bash-debug

ports:
  # Used by ddev - local db clients
  - port: 3306
    onOpen: ignore
  # Used by projector
  - port: 6942
    onOpen: ignore
  # Used by MailHog
  - port: 8027
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore
  # projector port
  - port: 9999
    onOpen: open-browser
